### PR TITLE
A lot of fixes, including fixing installation on macOS (does not support cp -u) and relative path resolution

### PR DESCRIPTION
**Pull request by illwieckz**
Most important things are:

- fix installation on macOS (macOS does not support `cp -u`)
- fix relative path resolution (install relatively to current directory, not relatively to some project subdirectory)
- abort properly on missing tools (do not try to use known missing tools)

Also:

- abort properly on errors (only half of the scripts was doing it)
- secure many strings using proper quotes
- use more portable shebang
- properly test for command availability using `command` shell builtin
- better way to get script directory
- install missing tools with `brew` on macOS

Your theme is useful to render GTK2 apps properly on macOS:

[NetRadiant on macOS](https://dl.illwieckz.net/b/netradiant/improvements/macos/20201223-043449-000.netradiant-macos.png)

[NetRadiant on macOS](https://dl.illwieckz.net/b/netradiant/improvements/macos/20201223-115554-000.netradiant-macos.png)

Which is far better than the default theme:

[NetRadiant on macOS](https://dl.illwieckz.net/b/netradiant/improvements/macos/20201223-135554-000.netradiant-macos.png)

So it's better if your macOS-like theme can be installed on macOS. =)

### CODE REVIEW

**Comment by vinceliuice** [comment]
Thank you for your work, but this theme is designed and used for the Linux system. After submitting your modification, it will not run in the Linux system. so I suggest you could build a project for the mac version on your github.

**Comment by vinceliuice** [comment]
Or you can pull this request into `macos` branch not the `master ` branch

**Comment by illwieckz** [comment]
This is not a mac version and this is bringing fixes for Linux too.

I'm a Linux user, I've tested this on Linux and did not have seen any problem after those changes, especially since this also fixes some problems on Linux.

This is not a “mac version”, nothing is modified in the theme, this PR submit programming fixes to the scripts in a way they don't fail on multiple OS, including Linux, macOS and FreeBSD.

This does not remove Linux compatibility, this fixes issues happening on Linux and add macOS and FreeBSD compatibility.

**Comment by illwieckz** [comment]
One of the Linux issue fixed by this PR is #174, this is the issue happening when sassc or other tools are not installed but the script does not exit if such tools are not installable or fail to install for some reasons.

It looks like other Linux issues I fixed were not reported yet, for example there was a bug on Linux making not possible to install on relative paths:

```sh
./install.sh -d ../somewhere
```

Only this worked:

```sh
./install.sh -d /absolute/path/to/somewhere
```

Installation on relative path is now fixed on Linux with this PR.

**Comment by vinceliuice** [comment]
Wow! that's great! thanks

**Comment by vinceliuice** [comment]
Wow! that's great! thanks

**Pull request merged**
